# Use postgres/example user/password credentials
services:
  app:
    build: .
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: qr-itemsfind
